### ISSUE TITLE
No warning if a hook is not marked as executable

### ISSUE THREAD

**Issue by chocol4te** [rhysd/cargo-husky#10]
I was getting the following error until I remembered to mark the hook as executable.
```
Error: User hooks directory is not found or empty: ...
```

A warning or clearer error message would be nice :)

**Comment by rhysd** [comment]
Please describe exact steps to reproduce this. Do you use `user-hooks`? In the case, cargo-husky does not care which file is for hook because cargo-husky does not know. It just copies executable files to `.git/hooks` and I think it should be intended behavior. Otherwise, we need to keep and maintain names of hook files of Git. But it's hard because it's up to Git version.

**Comment by chocol4te** [comment]
Sorry, I wasn't clear.

If you clone this repo: https://github.com/chocol4te/husky-issue and run `cargo test`, the expected behaviour is that the pre-commit hook in `.cargo-husky/hooks` folder is copied to `.git/hooks`, instead I get the following:

```
   Compiling cargo-husky v1.4.0
   Compiling husky-issue v0.1.0 ({path_to_repo}/husky-issue)
error: failed to run custom build command for `cargo-husky v1.4.0`
process didn't exit successfully: `{path_to_repo}/husky-issue/target/debug/build/cargo-husky-a19a1300231c7d87/build-script-build` (exit code: 1)
--- stderr
Error: User hooks directory is not found or empty: "{path_to_repo}/husky-issue/.cargo-husky/hooks"
```

**Comment by rhysd** [comment]
Your point is that error message is unclear, am I correct? If so, I think we can improve the error message something like

```
Error: User hooks directory is not found or no executable file is found in the directory. Did you forget making hook script executable?
```

My point is cargo-husky does not know which file is for hook and which is not for hook. It regards executable file as hook script without checking file name. So, for example, let's say we have two hooks `pre-commit` and `pre-push` scripts in hooks directory and forgot adding executable attribute to `pre-push`. In the case, cargo-husky only copies `pre-commit` file. Missing `pre-push` is not detectable.

**Comment by chocol4te** [comment]
Yes, that looks great :)

I can open a PR to change it?

**Comment by rhysd** [comment]
Of course. Thank you.
