### ISSUE TITLE
Please release 1.5 to crates.io

### ISSUE THREAD

**Issue by gilescope** [rhysd/cargo-husky#19]
#8 is fixed but not released yet. Please could another release hit crates.io?

**Comment by gilescope** [comment]
Just want to say how excellent this crate is @rhysd - it's saved me lots of time already!

**Comment by rhysd** [comment]
Fixed at 0dd33a5b0cf949f48f9d8234e95bb8d5b4219ce9.

Since I focused on critical issue of github-action-benchmark, sorry for the delay.
