### ISSUE TITLE
Adopt cargo subcommand rather than build script hack

### ISSUE THREAD

**Issue by kenoss** [rhysd/cargo-husky#21]
I guess build script is suitable at the time this repo was started.  But it's a time for modernizing.

## Problem

Currently cargo-husky is implemented as build script.  But I think this method is not appropriate for what we're solving.

Cons:

- AFAIK, build.rs is triggered just once if the user does not delete compile cache.  So, user-defined hooks may be not up to date.
- Entry point, e.g. `cargo test`, is not intuitive.
- Arbitrary code execution in `build.rs` is possibly dangerous.  https://twitter.com/Linda_pp/status/1183937002497953793
- In the case `cargo-husky` were broken, users face errors in compile time.  `cargo-husky` is not a very core module of Rust itself.  So I think loose coupling is better.
- Lots of crates named `cargo-*` are designed to be cargo subcommands.  See https://github.com/rust-lang/cargo/wiki/Third-party-cargo-subcommands
- Original `husky` is designed to be a npm subcommand.
- Controlling what to do in `Cargo.toml` is not flexible.  I prefer npm way, i.e., use JSON or YAML.
- ... any others?

## Proposal

Re-design it for cargo subcommand.  This will break foundation of this repo and cause big rewrite.

We'll provide `cargo husky` subcommand like `cargo husky pre-commit`.  This will read the config file in repo, and do some work.  Lots of cases are treated well by the config file and users can manage only that file.  Also, it will support user-defined hooks as well by let users put hook files under `.cargo-husky` directory, and each file call `cargo husky hogehoge` in that file manually.  For example, `hogehoge = pre-commit` for `.cargo-husky/pre-commit` file.

@rhysd Any thoughts?

I want to do but, unfortunately, I'm sorry that I do not have much time to accomplish this in Feb I guess.

**Comment by kenoss** [comment]
And, `cargo husky sync-user-defined-hooks` will sync user-defined hooks.  Users can manage this transparently by triggering this command in `cargo husky pre-commit` or something else.

**Comment by kenoss** [comment]
> Controlling what to do in Cargo.toml is not flexible. I prefer npm way, i.e., use JSON or YAML.

I mean, we shouldn't abuse feature gates.  Appropriate use of TOML will be a candidate.

**Comment by ubnt-intrepid** [comment]
Alternatively, how about switching to the library and expose the common features in `build.rs`? [`cargo-xtask`](https://github.com/matklad/cargo-xtask) is a good example of definition the project-specific Cargo subcommands in a free form.

**Comment by kenoss** [comment]
Makes sense.  Now we have options global way (`npm install -g`) and project local way (`npm install`), right?

**Comment by ubnt-intrepid** [comment]
Yes. In that case, we can implement the variant of cargo subcommand as a CLI wrapper for the library.

**Comment by rhysd** [comment]
> Arbitrary code execution in build.rs is possibly dangerous.

This is not related to this crate. It's a problem of Rust itself.

**Comment by rhysd** [comment]
> Original husky is designed to be a npm subcommand.

That's not true. There is no way to add new subcommand to `npm`.

**Comment by rhysd** [comment]
When making this crate `cargo husky` subcommand, this crate will loose the important benefit that it forces to set hooks. Users need to run `cargo husky` command manually to setup hooks and it means that they *may* forget setting hooks.

When we making this as subcommand, then what is the main profit against preparing a tiny shell script which sets Git hooks? I'm not seeing the real-world problem which this issue wants to resolve yet. The cons point I agree is:

> Entry point, e.g. cargo test, is not intuitive.

But making a new subcommand would sacrifice the above benefit only for the intuition. Is there any real-world issue due to this? Does it really worth to solve?

> Alternatively, how about switching to the library and expose the common features in build.rs?

That's possible. But it would make compiling dependencies slow and make maintenance harder (due to managing multiple crates in workspaces) so I don't want to do it until it is really necessary.

> I want to do but, unfortunately, I'm sorry that I do not have much time to accomplish this in Feb I guess.

Me too. That's the reason [I mark this crate's maintenance state as 'passibly-maintained'](https://github.com/rhysd/cargo-husky/blob/master/Cargo.toml#L21).

**Comment by kenoss** [comment]
Thanks for reply.

> And I'm not seeing the real-world problem which this issue wants to resolve yet. The cons point I agree is:
> > Entry point, e.g. cargo test, is not intuitive.

The other main point is:

> AFAIK, build.rs is triggered just once if the user does not delete compile cache. So, user-defined hooks may be not up to date.

Isn't it correct?  I know that automatic installation by `cargo test` is useful, but using hooks not up to date could be a misstep and dangerous.

> When making this crate cargo husky subcommand, this crate will loose the important benefit that it forces to set hooks.

Providing cargo subcommand does not imply we cannot force automatic installation, e.g. by separating crates.

1. We provide cargo subcommand, for example, globally.  I mean, users or CI has to be install `cargo husky` somehow.  (Is there a way to ensure this?) Let name of this crate be `cargo-husky-subcommand`.
2. We run bootstrapping hook installation in `cargo test` by devdependency.  Let name of this crate be `cargo-husky-bootstrap`.  Hooks are shell script with one line, something like `cargo husky hoge-bootstrap` for `.git/hooks/hoge`. (Naming is TBD.)
3. `cargo husky hoge-bootstrap` runs hooks defined in config file (by calling `cargo husky hoge`) and user-defined hooks appropriately.

> Me too. That's the reason I mark this crate's maintenance state as 'passibly-maintained'.

It's a new for me.  Thanks.

**Comment by rhysd** [comment]
> Isn't it correct? I know that automatic installation by cargo test is useful, but using hooks not up to date could be a misstep and dangerous.

Yes, correct. I apologize that I missed the point and actually it is confusing. I don't know what 'dangerous' means, tho.


It seems that my intention is not caught well. In short, without the feature which automatically sets hooks, I feel cargo-husky doesn't worth existing.

It's enough to put the shared hook script in `./scripts/pre-push.sh` and to prepare small tiny script like below:

```sh
#! /bin/bash

echo 'Linking hook scripts...'
ln -s ./scripts/pre-push.sh .git/hooks/pre-push
echo 'Done.'
```

Or it might be enough simply to write documentation which says 'Run `ln -s ./scripts/pre-push.sh .git/hooks/pre-push`'.

So,

> Is there a way to ensure this?

This point in 1. is the most important for me. And for other parts, I'm honestly not seeing advantages against above tiny shell script.

**Comment by rhysd** [comment]
Closing as inactive.
