### ISSUE TITLE
request: disable through env variable

### ISSUE THREAD

**Issue by mehcode** [rhysd/cargo-husky#6]
awesome tool. was just looking for a husky for cargo.

Any chance you can add like a `HUSKY_DISABLE=1` flag or similar that we can opt-out to force a commit? Or does this exist and I didn't find it?

**Comment by rhysd** [comment]
Please use `--no-verify` option of `git push` and `git commit`. Doesn't it work for you?

**Comment by mehcode** [comment]
Oh. I'm an idiot. Don't mind me. I completely forgot git can do that. I was looking for an option in husky. Thanks.
